# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-18 17:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighbourhood', '0004_auto_20181018_2030'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hood',
            new_name='Jirani',
        ),
        migrations.RenameField(
            model_name='business',
            old_name='hood',
            new_name='jirani',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='hood',
            new_name='jirani',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='hood',
            new_name='jirani',
        ),
    ]
