# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-18 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbourhood', '0005_auto_20181018_2044'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='name',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='business',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
