# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-23 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0003_auto_20181023_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighbourhood',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='hood_pic/'),
        ),
    ]
