# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-23 14:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0004_auto_20181023_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='neighbourhood',
            name='picture',
        ),
    ]
