# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-23 10:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0023_auto_20181023_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighbourhood',
            name='hood_pic',
            field=models.ImageField(blank=True, default=0, null=True, upload_to='hood_pic/'),
        ),
    ]
